library(httr)
library(XML)

yahoo_get_league_standing <- function(){
  
# Load Signature generated by yahooFantasy_get_credential -----------------------------
  load("Fantasy.Rdata");
  
# Construct URI for connecting to your league (should abstract into its own function) ---
  game_ID <-370; # MLB 2017. You can get this by querying http://fantasysports.yahooapis.com/fantasy/v2/game/mlb
  league_ID <-30362; # League ID. See your league settings.
  leagueKey  <- paste(game_ID,'.l.',league_ID,sep='');
  
  baseURL <- "http://fantasysports.yahooapis.com/fantasy/v2/league/";
  specURL <- "/standings";
  fullURL <- paste(baseURL,leagueKey,specURL,sep='');
  
# Fetch data --------------------------------------------------------------------------
  page <-GET(fullURL,config(token=yahoo_token));
  retrievedXml <- content(page, as="text", encoding="utf-8");
  standingsInfo <- xmlTreeParse(retrievedXml, useInternal=TRUE);

}